#define WAITING_KITCHEN 6000
#define WAITING_BATHROOM 100
#define DISTANCE_ULTRASONIC 60

#define PIN_PIR 2
#define PIN_TRIG 3
#define PIN_ECHO 4
#define PIN_RELAY_KITCHEN 5
#define PIN_RELAY_BATHROOM 6

#define SERIALMONITOR true